version: "3.9"

services:
  calculadora-backend:
    image: calculadora-backend
    container_name: calculadora-backend
    ports:
      - "8080:8080"
    networks:
      - calculadora-network

networks:
  calculadora-network:
    external: true
